# Generated by Django 5.1.15 on 2026-02-17 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="provinces/"),
                ),
                ("headquarters", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TrekkingRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=300)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("hard", "Hard"),
                            ("extreme", "Extreme"),
                        ],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(help_text="Number of days"),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Distance in kilometers",
                        max_digits=6,
                    ),
                ),
                (
                    "max_altitude",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum altitude in meters"
                    ),
                ),
                (
                    "best_season",
                    models.CharField(
                        choices=[
                            ("spring", "Spring (Mar-May)"),
                            ("summer", "Summer (Jun-Aug)"),
                            ("autumn", "Autumn (Sep-Nov)"),
                            ("winter", "Winter (Dec-Feb)"),
                            ("all", "All Seasons"),
                        ],
                        default="autumn",
                        max_length=10,
                    ),
                ),
                ("start_point", models.CharField(max_length=100)),
                ("end_point", models.CharField(max_length=100)),
                (
                    "price_per_person",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in USD", max_digits=10
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="routes/"),
                ),
                (
                    "highlights",
                    models.TextField(
                        blank=True, help_text="Key highlights, one per line"
                    ),
                ),
                (
                    "includes",
                    models.TextField(
                        blank=True, help_text="What is included, one per line"
                    ),
                ),
                (
                    "excludes",
                    models.TextField(
                        blank=True, help_text="What is excluded, one per line"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="treks.province",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("nationality", models.CharField(max_length=100)),
                ("trek_start_date", models.DateField()),
                ("trek_end_date", models.DateField()),
                ("num_trekkers", models.PositiveIntegerField(default=1)),
                ("require_guide", models.BooleanField(default=False)),
                ("require_porter", models.BooleanField(default=False)),
                ("num_porters", models.PositiveIntegerField(default=0)),
                ("special_requests", models.TextField(blank=True)),
                ("emergency_contact_name", models.CharField(max_length=200)),
                ("emergency_contact_phone", models.CharField(max_length=20)),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "booking_reference",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="treks.trekkingroute",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
